---
- hosts: webservers
  become: yes
  become_user: "{{ deploy_user }}"
  vars_files:
    - "../vars/main.yml"
  tasks:
    - name: "Downgrading to {{ app_vsn }}"
      command: "./bin/{{ app_name }} downgrade {{ app_vsn }}"
      args:
        chdir: "{{ deploy_dir }}"

    - name: Restart systemctl
      raw: sudo /bin/systemctl restart {{ app_name}}
