---
- hosts: all
  gather_facts: False
  become: yes
  vars_files:
    - "../vars/main.yml"
  tasks:
    - name: Install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: "Add {{ deploy_group }} group"
      group: name={{ deploy_group }} state=present

    - name: "Add {{ deploy_user }} user"
      user: name={{ deploy_user }} groups={{ deploy_group }} append=yes state=present

    - name: Create deploy dirs
      file: path={{ item }} state=directory owner={{ deploy_user }} group={{ deploy_user }} mode=0700
      with_items: "{{ deploy_dirs }}"

    - name: Create sudoers config for deploy user
      template:
        src: "../templates/sudoers.j2"
        dest: /etc/sudoers.d/{{ deploy_user }}-{{ app_name }}
        owner: root
        group: root
        mode: 0600

    - name: Copy systemd config file
      template:
        src: "../templates/systemd.j2"
        dest: "/etc/systemd/system/{{ app_name }}.service"
        owner: root
        group: root
        mode: 0644

    - name: Enable service
      service: name={{ app_name }} enabled=yes

    - name: "Forward port 80 to {{ app_port }}"
      iptables:
        table: nat
        chain: PREROUTING
        in_interface: eth0
        protocol: tcp
        match: tcp
        destination_port: 80
        jump: REDIRECT
        to_ports: "{{ app_port }}"
        comment: "Redirect web traffic to port {{ app_port }}"

