---
- hosts: webservers
  become: yes
  become_user: "{{ deploy_user }}"
  vars_files:
    - "../vars/main.yml"
  tasks:
    - name: "Check if {{ app_vsn }} dir exists"
      stat:
        path: "{{ releases_dir }}/{{ app_vsn }}"
      register: new_release_dir

    - name: "Create {{ app_vsn }} dir"
      file: path="{{ releases_dir }}/{{ app_vsn }}" state=directory
      when: not new_release_dir.stat.exists

    - name: Copy tarbal to webserver
      copy: src={{ app_local_path }} dest="{{ releases_dir }}/{{ app_vsn }}/"
      when: not new_release_dir.stat.exists

    - name: "Upgrading to {{ app_vsn }}"
      command: "./bin/{{ app_name }} upgrade {{ app_vsn }}"
      args:
        chdir: "{{ deploy_dir }}"

    - name: Restart systemctl
      raw: sudo /bin/systemctl restart {{ app_name}}

